
name: REST Tests & Deploy

on: 
  # push: 
    #  branches:
      # - '*'
      # - '!main'
  pull_request:
    branches: [ master ]

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Test Docker Container
        run: docker build . --file dev.Dockerfile --tag petclinic-rest-test
      - name: Run Test Docker Container
        run: docker run -d --name petclinic-rest-test -p 9966:9966 petclinic-rest-test:latest 
      - name: Rest Unit Tests
        run: docker exec -w /spring-petclinic-rest/ petclinic-rest-test mvn test

      - name: Setup Node Enviroment
        uses: actions/setup-node@v1
        with: 
          node-version: '12.x'
      - name: Install Newman for API Tests
        run: npm install -g newman
      - name: Run API Tests
        run: newman run https://www.getpostman.com/collections/db06d79b830bd6deb84e

  Deploy-on-Heroku:
    needs: Tests
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: AkhileshNS/heroku-deploy@v3.11.10
        with:
          dontuseforce: false
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "spring-boot-hsbremen"
          heroku_email: "inopa@web.de"
          usedocker: true