
name: Heroku Rest Build & Deploy

on: 
  push: 
     branches:
      - '*'
      - '!main'
  pull_request:
    branches: [ master ]

jobs:
  Build-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Test Docker 
        run: docker build . --file dev.Dockerfile --tag petclinic-rest-test
      - name: Run Test Docker 
        run: docker run -d --name petclinic-rest-test -p 9966:9966 petclinic-rest-test:latest 
      - name: Unit Test
        run: docker exec -w /spring-petclinic-rest/ petclinic mvn test

      - name: Setup Node-enviroment for Postman Tests 
        uses: actions/setup-node@v1
        with: 
          node-version: '12.x'
      - name: Install Newman  
        run: npm install -g newman
      - name: Run Postman Tests
        run: newman run https://www.getpostman.com/collections/db06d79b830bd6deb84e



        
